openapi: 3.0.0
info:
  title: SentinelOne
  description: Provides information contained in SentinelOne related to agents, applications and more".
  version: 'v1'
servers:
  - url: https://usea1-007.sentinelone.net
paths:
  /web/api/v2.1/agents:
    get:
      operationId: Get_Agent
      summary: Get Agent      
      parameters:
      - in: query
        name: id
        schema:
          type: string
        required: true
        description: 'The Agent ID. Example: "225494730938493804".'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAgentResponse'
components:
  schemas:
    getAgentResponse:
      type: object
